export { default as AdminLogin } from './AdminLogin'
export { default as Dashboard } from './Dashboard'
export { default as Management } from './Management'
export { default as QueueCreation  } from './QueueCreation'
export { default as Flashboard } from './Flashboard'
export { default as Window } from './Window'
export { default as Archives } from './Archives'
export { default as Station} from './Station'